### ISSUE TITLE
Document - In "Quick Fact", please set fields on empty mode instead of first item of the list 

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#187]
In current view, the country/year, Displacement/Type are pre-set. This can cause mistakes. Please, can the fields be empty or alternatively set on "Select"? Many thanks

**Comment by allochi** [comment]
This took sometime, I had to add validation to the QuickFact to make sure that all these fields will be filled before submission.

This introduced some breaking changes, but a positive one, since the changes enhanced the way the form validate data before submission, the same enhancement will be introduced to other forms.
 (technical: this involved solving the problem of nested properties validation)

expected update v2.0-beta.4
