### ISSUE TITLE
Question about data migration

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#67]
I’m not sure if this is how it is supposed to be: I had one event for Kosovo, with one report and one document. That was migrated, to: one document, one fact (associated to a master fact and to no events), and one master fact (with the sub fact, and associated to an event). It’s not clear to me why a master fact was created and why the sub fact is not associated to the event.

**Comment by allochi** [comment]
This is intentional, since I wanted to keep all the information from the older system, I can't merge the facts together, because I don't know which one to keep, so basically I kept both, with the fact that used to be in an event attached to the event, and the fact from the report attached as a sub-fact.

In the review process, you decide which one you want to keep master/sub and we can delete the other.

**Comment by andreslizcano** [comment]
Ok.
