### ISSUE TITLE
Suggestions for new DB functionality

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#70]
1. When adding a fact from a document, can I be sent immediately to that fact? 
2. Review comments: When I comment in the REVIEW section, the comment is only saved in the HISTORY tab, not in the Reviews tab, like all other actions. If the comments are meant to generate action by other people, I suggest they’re put somewhere more visible. If you have to change tab to go and look for them, they might get lost. 
3. Reporting and Data tab of a Fact have repetitive information - They could be merged. If not, it would be important to clarify why the information is necessary.

**Comment by ghost** [comment]
While Ali explained the issue with review comments, I also agree with Andres about making the comments more visible on the first screen rather than flipping through tabs to see the comments. Also it would be good to have comments... do you actually need a history tab? Or can it all just be on one screen... kind of a like a forum style... so you can read what comments and actions have been taken in a chronological order?
